import Image from "next/image";

const certificates=[
  {src:"/images/certificazioni/affitti-brevi.png",title:"Competenza negli affitti brevi",text:"Attestato di competenza rilasciato tramite ente accreditato da Regione Lombardia.",meta:"Regione Lombardia · 2024"},
  {src:"/images/certificazioni/agente-immobiliare.png",title:"Agente d’affari in mediazione",text:"Idoneità per il settore immobiliare presso la Camera di Commercio Milano Monza Brianza Lodi.",meta:"Camera di Commercio · 2026"},
  {src:"/images/certificazioni/amministratore-condominio.png",title:"Amministratore condominiale e immobiliare",text:"Corso abilitante di 80 ore e prova finale superata presso ente accreditato.",meta:"ICAF · 2025"},
];

const proof=[
  {src:"/images/social-proof/profilo-host.jpg",alt:"Profilo Ciovati Group con 910 recensioni e valutazione 4,71",title:"910 recensioni e valutazione 4,71",text:"Esperienza operativa maturata nell’ospitalità come Ciovati Group."},
  {src:"/images/social-proof/superhost.jpg",alt:"Riconoscimento Superhost ricevuto da Luca",title:"Riconoscimento Superhost",text:"Un segnale concreto di affidabilità, rapidità di risposta e qualità dell’esperienza."},
];

export default function FounderProof(){return <section className="section bg-navy" aria-labelledby="founder-proof-title"><div className="container"><p className="eyebrow">ESPERIENZA DOCUMENTATA</p><h2 id="founder-proof-title" className="display mt-4 max-w-4xl text-5xl font-bold sm:text-7xl"><span className="block">Prima del metodo, c’è il mestiere.</span><span className="mt-2 block text-emerald-400">E ci sono le prove.</span></h2><div className="mt-6 max-w-3xl space-y-2 text-lg leading-8 text-muted"><p>Le competenze di Luca non restano scritte in una lista.</p><p>Qui trovi le qualifiche e i riscontri operativi che sostengono l’esperienza di Ciovati Group.</p></div><div className="mt-12 grid items-stretch gap-5 lg:grid-cols-3">{certificates.map(c=><article key={c.title} className="glass flex h-full flex-col overflow-hidden rounded-3xl"><div className="relative aspect-[2.5/1] bg-white"><Image src={c.src} alt={`Estratto pubblico dell’attestato: ${c.title}`} fill className="object-cover object-top" sizes="(max-width:1024px) 100vw, 33vw"/></div><div className="flex flex-1 flex-col p-6"><h3 className="display text-2xl font-bold">{c.title}</h3><p className="mt-3 leading-7 text-muted">{c.text}</p><p className="mt-auto pt-5 text-xs font-bold uppercase tracking-[.16em] text-emerald-400">{c.meta}</p></div></article>)}</div><div className="mt-16 flex items-end justify-between gap-6"><div><p className="eyebrow">RISCONTRI DAL CAMPO</p><h3 className="display mt-3 text-4xl font-bold sm:text-5xl"><span className="block">Non teoria.</span><span className="text-sky">Operatività quotidiana.</span></h3></div><p className="hidden max-w-sm text-right text-sm leading-6 text-muted md:block">Scorri per vedere il profilo host e il riconoscimento Superhost.</p></div><div className="proof-scroll mt-8 flex snap-x gap-5 overflow-x-auto pb-5">{proof.map(p=><figure key={p.title} className="glass flex min-w-[86%] snap-center flex-col overflow-hidden rounded-3xl sm:min-w-[65%] lg:min-w-[42%]"><div className="relative aspect-[4/3] bg-white"><Image src={p.src} alt={p.alt} fill className="object-contain" sizes="(max-width:768px) 86vw, 48vw"/></div><figcaption className="flex-1 p-6"><p className="display text-2xl font-bold">{p.title}</p><p className="mt-2 text-sm leading-6 text-muted">{p.text}</p></figcaption></figure>)}</div><div className="mt-5 space-y-1 text-xs leading-5 text-muted"><p>Le anteprime degli attestati sono state limitate alle sole informazioni professionali per proteggere i dati personali.</p><p>Dati e risultati si riferiscono ai documenti e agli screenshot forniti e possono variare nel tempo.</p></div></div></section>}
